### ISSUE TITLE
Plugins are not working or not configurable

### ISSUE THREAD

**Issue by johny-mnemonic** [nunofgs/rpi-octoprint#12]
Since https://github.com/nunofgs/docker-octoprint/pull/9 plugin settings is not working for installed plugins and some are not working at all. It was already mentioned in https://github.com/nunofgs/docker-octoprint/issues/5.
This is sad, as I was really happy when I saw you did this change:-(

**Comment by nunofgs** [comment]
@johny-mnemonic I just pushed a fix for this (on tags `1.3.10` and `latest`). Sorry about the issue. Please test it with all your plugins and let me know if it works for you.

PS: I'd recommend deleting all your plugins in `/data/plugins` and reinstalling them through Octoprint to make sure you're testing from a clean state.

/cc @reloxx13

**Comment by johny-mnemonic** [comment]
@nunofgs Thanks for fast fix! It seems to work.
While installing filament manager plugin it reported it as "unknown", while other plugins are now reported by it's name, but even the filament manager plugin seems to work without any issue.
I think the best confirmation is, that while previously I was unable to list installed plugins using pip on command line, I can now list them all just fine.

**Comment by nunofgs** [comment]
Fantastic. Happy to hear that! 🎉
