### ISSUE TITLE
Unable to display raspberry pi camera output

### ISSUE THREAD

**Issue by plapointe6** [nunofgs/rpi-octoprint#15]
Hello,

I am trying to make this docker image works with the official Raspberry PI camera module.

Do someone managed to get the rpi camera to display in mjpg-streamer ?

I tryed to replace input_uvc.so by input_raspicam.so but input_raspicam.so do not compile in the image creation process.

Thanks !

**Comment by nunofgs** [comment]
Hi @plapointe6,

I don't actually own a raspberry pi camera module so can't really be much of a help here. I'll accept any contributions that fix the issue though!

**Comment by plapointe6** [comment]
I managed to make it work after many headache. See PR #16
