### ISSUE TITLE
The fontconfig package is missing.

### ISSUE THREAD

**Issue by Blazin64** [nunofgs/rpi-octoprint#20]
As far as I know, this only affects people using the Octolapse plugin. Octolapse has an option to overlay text on time lapse videos, but it does not work unless the fontconfig package is installed. I manually installed fontconfig in the container to confirm this.

The fontconfig package has no extra dependencies, so adding it to the Dockerfile should be fairly straightforward.

**Comment by nunofgs** [comment]
Confirmed that it doesn't add much to the image. Since I'm not the "official" octoprint image I don't mind adding a bit of extra usefulness here and there. Thanks :)
