### ISSUE TITLE
unable to start webcam/streaming

### ISSUE THREAD

**Issue by datajerk** [nunofgs/rpi-octoprint#3]
Errors:

```
# supervisorctl start mjpeg-streamer
Error: .ini file does not include supervisorctl section
```

If I add a blank supervisorctl section to /etc/supervisor/supervisord.conf, then I get the following error:

```
# supervisorctl start mjpeg-streamer
error: <class 'socket.error'>, [Errno 99] Address not available: file: /usr/local/lib/python2.7/socket.py line: 575
```

Same error from webpage controls.

Running:

```
mjpg_streamer -i "/usr/local/lib/mjpg-streamer/input_uvc.so -r 640x480 -d /dev/video0" -o "/usr/local/lib/mjpg-streamer/output_http.so -w /usr/local/www -p 8080"
```

manually does work.

Platform: RPI3
Video: /dev/video0

**Comment by nunofgs** [comment]
Thanks for bringing this to my attention. This was due to the 3.x upgrade of supervisorctl.

I've fixed the issue and pushed new images. Please give it a go 😄

**Comment by datajerk** [comment]
Thanks, works great.
