### ISSUE TITLE
Backup in wrong (unmapped) location

### ISSUE THREAD

**Issue by ModischFabrications** [nunofgs/rpi-octoprint#32]
As I understand it this image has restructured the data directory to use /data. Creating a backup using the build-in backup tool with the command line stores the *.zip in the old directory, which is `/root/.octoprint/data/backup/octoprint-backup-20191008-210723.zip`. 

Backups using the Web-UI are stored correctly in `data/backup/`.

Reproduction:
[1. recommended init]
2. Backup using Web-UI -> `/data/backup/octoprint-backup-20191008-210647.zip`
3. Backup using command line (`docker exec -it modischpi_octoprint_1 bash` [...] `octoprint plugins backup:backup`)-> `/root/.octoprint/data/backup/octoprint-backup-20191008-210723.zip`

It would be nice to have this command remapped as well. My current workaround would be to manually copy the zip into the target directory or mount the new backup as another volume.

**Comment by nunofgs** [comment]
Fixed, thank you.
