### ISSUE TITLE
Plugins gone

### ISSUE THREAD

**Issue by reloxx13** [nunofgs/rpi-octoprint#5]
Heya,

after alot of troubls while installing ( dude ur readme sucks :D ), its finally working fine.

But while configuring at some points the installed plugins get lost.

Looks like plugins does not get installed in the data dir and getting removed after some image recreations.

The plugin config itself is stored in config.yml and everything is fine again after reinstalling all plugins.

**Comment by nunofgs** [comment]
The reason this is happening is that Octoprint uses `pip` to install plugins. Since you're not the first to report this, I decided to tackle this. Thanks!

**Comment by reloxx13** [comment]
great work! now one more time installing all plugins :D

i checked and can confirm the plugins are not inside the data directory (which is the volume).

**Comment by reloxx13** [comment]
im sorry but this is not working very well, i had to remove that change local.

this is cuzing problems for alot of addons (e,g, themeify).
